name: PHP Lint

on:
  push:
    paths:
      - '**/*.php'
      - '.github/workflows/php-lint.yml'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Validate PHP syntax
        run: |
          php -l dobity-baterky.php
          find includes -name '*.php' -print0 | xargs -0 -n1 php -l
          if [ -d assets ]; then
            find assets -name '*.php' -print0 | xargs -0 -r -n1 php -l
          fi
